# Generated by Django 3.1.5 on 2021-01-17 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the Note.', max_length=100, unique=True)),
                ('published_at', models.DateTimeField(auto_now_add=True, help_text='publishing date')),
                ('body', models.TextField(help_text='Main blog')),
                ('draft', models.BooleanField(default=False, help_text='Draft or published note')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Edited and published at')),
                ('hidden', models.BooleanField(default=False, help_text='the file is hidden or private if set to true ')),
                ('writer', models.ForeignKey(help_text='Author of the note', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
